#!/bin/bash

#Run with:
#eval "$(curl -fsSL -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/atomjump/medimage_export/master/install)"

#Update the main loop-server - for vertical images
sudo git -C /jet/www/default/vendor/atomjump/loop-server pull

#Get the plugin installed
sudo git -C /jet/www/default/vendor/atomjump/loop-server/plugins/ clone https://github.com/atomjump/medimage_export.git

#Permissions
sudo chmod 777 /jet/www/default/vendor/atomjump/loop-server/plugins/medimage_export/temp


#Create a config file for the new plugin
sudo echo "{ \"serverPath\": \"/jet/www/default/vendor/atomjump/loop-server/\", \"staging\": true, \"phpPath\": \"/jet/bin/php\" }" > medimage_config.json
sudo cp medimage_config.json /jet/www/default/vendor/atomjump/loop-server/plugins/medimage_export/config/config.json


#Insert the medimage_export plugin into the plugins array 
mkdir ~/medimage_export
sudo cp /jet/www/default/vendor/atomjump/loop-server/config/config.json ~/medimage_export/
sudo sed -ie 's/\"emoticons_basic\",/\"emoticons_basic\",\n\t\t\"medimage_export\",/g' ~/medimage_export/config.json
sudo cp ~/medimage_export/config.json /jet/www/default/vendor/atomjump/loop-server/config/config.json