#!/bin/bash

#Run with:
#eval "$(curl -fsSL -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/atomjump/medimage_export/master/install)"

#Update the main loop-server - for vertical images
sudo git -C /jet/www/default/vendor/atomjump/loop-server pull

#Get the plugin installed
sudo git -C /jet/www/default/vendor/atomjump/loop-server/plugins/ clone https://github.com/atomjump/medimage_export.git

#Permissions
sudo chmod 777 /jet/www/default/vendor/atomjump/loop-server/plugins/medimage_export/temp

